kind: step-type
version: "1.0"
metadata:
  name: deploy
  version: 0.0.1
  isPublic: true
  description: Deploy
  sources:
    - 'https://github.com/codefresh-io/steps/tree/master/graduated/deploy'
  stage: graduated
  official: true
  categories:
    - featured
    - k8
  icon:
    type: svg
    url: https://cdn.jsdelivr.net/gh/codefresh-io/steps/graduated/deploy/icon-2.svg
    background: "#326DE6"
  maintainers:
    - name: Codefresh INC
  examples:
    - workflow:
        version: '1.0'
        steps:
            Deploy:
              title: deploying to cluster
              type: deploy
              arguments:
                kind: kubernetes
                cluster:  myDemoAKSCluster
                namespace: demo
                service: my-python-app
spec:
  arguments: |
    {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "definitions": {},
        "type": "object",
        "additionalProperties": true,
        "patterns": [],
        "required": ["kind", "cluster", "namespace"],
        "properties": {
            "kind": {
                "type": "string",
                "description": "Currently only kubernetes is supported"
            },
            "cluster": {
                "type": "string",
                "description": "Name of your K8s cluster as found in the dashboard"
            },
            "namespace": {
                "type": "string",
                "description": "Namespace where the deployment will take place"
            },
            "file_path": {
                "type": "string",
                "description": "A deployment manifest. You need to provide service OR file_path"
            },
            "timeout": {
                "type": "number",
                "description": "Seconds to wait for the deployment to be completed. Default is 120 seconds"
            },
            "service": {
                "oneOf": [{
                    "type": ["array", "boolean", "number", "object", "string", "null"]
                }, {
                    "type": "string"
                }],
                "description": "Name of the existing service that will updated. You need to provide service OR file_path"
            },
            "candidate": {
                "type": "object",
                "properties": {
                    "image": {
                        "type": "string"
                    },
                    "registry": {
                        "type": "string"
                    }
                },
                "examples": ["image: ${{build_step}}\nregistry: dockerhub"],
                "additionalProperties": false,
                "patterns": [],
                "required": ["image", "registry"],
                "description": "Docker image that will be deployed. Only valid if service is defined. Should contain image and name of registry as it appears in the <a href=\"https://codefresh.io/docs/docs/docker-registries/external-docker-registries/\">registry integration page</a>."
            }
        }
    }
