kind: step-type
version: '1.0'
metadata:
  name: helm
  version: 0.1.1
  isPublic: true
  description: Release a Helm chart (update or install)
  sources:
    - 'https://github.com/codefresh-contrib/cfstep-helm'
  stage: incubating
  maintainers:
    - name: Roman Kuchuk
      email: r.kuchuk@codefresh.io
  categories:
    - featured
  official: false
  tags: []
  icon:
    type: image
    size:
      large:
        url: >-
          https://cdn.jsdelivr.net/gh/codefresh-io/steps/incubating/helm/icon.jpg
  examples:
    - description: example-1
      workflow:
          deploy:
            type: helm
            arguments:
              chart_name: test_chart
              release_name: first
              kube_context: my-kubernetes-context
              tiller_namespace: kube-system
              namespace: project
              custom_values:
                - KEY1=VAL1
                - KEY2=VAL2
                - KEY3=VAL3
              custom_value_files:
                - /path/to/values.yaml
                - /path/to/values2.yaml
              cmd_ps: --wait --timeout 5
    - description: example-2
      workflow:
          deploy:
            type: helm
            arguments:
              ACTION: install
              chart_name: test_chart
              release_name: first
              kube_context: my-kubernetes-context
              custom_values:
                - pat.arr="{one,two,three}"
                - STR_WITH_COMAS="one\,two\,three"
spec:
  arguments: |-
    {
        "definitions": {},
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "additionalProperties": false,
        "patterns": [],
        "required": [
            "kube_context",
            "chart_name",
            "release_name"
        ],
        "properties": {
            "kube_context": {
                "type": "string",
                "description": "Kubernetes context to use (the name of the cluster as configured in Codefresh) (required)"
            },
            "chart_name": {
                "type": "string",
                "description": "Helm chart name to release (path to chart folder, or name of packaged chart) (required)"
            },
            "release_name": {
                "type": "string",
                "description": "Helm release name"
            },
            "action": {
                "type": "string",
                "description": "The helm operation mode is set by the ACTION variable, where the value is install/auth/push"
            },
            "namespace": {
                "type": "string",
                "description": "Target Kubernetes namespace"
            },
            "tiller_namespace": {
                "type": "string",
                "description": "Kubernetes namespace where tiller is at"
            },
            "chart_version": {
                "type": "string",
                "description": "Application chart version to install"
            },
            "helm_version": {
                "type": "string",
                "examples": ["2.9.1", "2.9.0"],
                "default": "2.9.1",
                "description": "Version of cfstep-helm image(also helm-cli version). You can choose specific image at https://hub.docker.com/r/codefresh/cfstep-helm/tags"
            },
            "chart_repo_url": {
                "type": "string",
                "description": "Helm chart repository URL (overriden by injected Helm repository context)"
            },
            "custom_value_files": {
                 "type": "array",
                 "items": {
                     "type": "string"
                  },
                  "description": "Values file to provide to Helm (as --values or -f). see usage information below"
            },
            "custom_values": {
                 "type": "array",
                 "items": {
                     "type": "string"
                  },
                  "description": "Variables to provide to Helm (as --set). see usage information below"
            },
            "cmd_ps": {
                "type": "string",
                "description": "Variable to provide other Helm cli flags. For example: '--wait --timeout', etc"
            }
        }
    }
  stepsTemplate: |-
    main:
      name: helm
      image: codefresh/cfstep-helm:[[ .Arguments.helm_version ]]
      environment:
      [[- range $key, $val := .Arguments -]]
      [[ if and (not (hasPrefix $key "custom_value_files")) (not (hasPrefix $key "custom_values")) ]]
        - '[[ toUpper $key ]]=[[ $val ]]'
      [[- end ]]
      [[- end -]]
      [[ range $arg := .Arguments.custom_values ]]
        - 'CUSTOM_[[ $arg ]]'
      [[- end -]]
      [[ range $key, $val := .Arguments.custom_value_files ]]
        - 'CUSTOMFILE_[[ toUpper $key ]]=[[ $val ]]'
      [[- end ]]
  delimiters:
    left: '[['
    right: ']]'
